# Generated by Django 3.0.4 on 2020-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Menu', 'Menu'), ('TarihiYerler', 'TarihiYerler'), ('Müzeler', 'Müzeler'), ('TatilBeldeleri', 'TatilBeldeleri')], max_length=20),
        ),
    ]
