# Generated by Django 3.0.4 on 2020-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200601_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('Menu', 'Menu'), ('TarihiYerler', 'TarihiYerler'), ('Muzeler', 'Muzeler'), ('TatilBeldeleri', 'TatilBeldeleri')], max_length=20),
        ),
    ]
