# Generated by Django 3.0.4 on 2020-06-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_ccomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccomment',
            old_name='comment',
            new_name='icomment',
        ),
        migrations.RenameField(
            model_name='ccomment',
            old_name='rate',
            new_name='irate',
        ),
        migrations.RenameField(
            model_name='ccomment',
            old_name='subject',
            new_name='isubject',
        ),
    ]
