# Generated by Django 3.0.4 on 2020-06-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200601_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccomment',
            old_name='icomment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='ccomment',
            old_name='irate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='ccomment',
            old_name='isubject',
            new_name='subject',
        ),
    ]
